# Metadata
title: "Le Shop des Abeilles"
favicon: assets/img/favicon.png
description: Une version customisée de la liste des objets du Toolkit pour supporter toutes les dernières fonctionalités de Utils.

baseurl: '/liste-jimmy' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ''
github_username: 'jimmynovaaa'
color_theme: auto

# Item list settings
#
# A brief overview of the settings in this section include:
store:
#   category    → Whether or not the item's in-game category willbe visible on the list.
#   weight      → Whether or not the item's purchase weight will be visible on the list.
#   karma       → Whether or not the product's karma type override will be visible on the list
#   usage       → Whether or not the list will display an example command on how to purchase the product.
#   quantity    → Whether or not the item's quantity limit will be visible on the list.
#   mod         → Whether or not the list will display the mod that added the product.
#   conflicts   → Whether or not the list will display any trait conflicts the trait has.
#   stats       → Whether or not the list will display any stats the trait has.
#   limit       → Whether or not the list will display when a trait can bypass the trait limit.
#   description → Whether or not the list will display the trait's description.
  traits:
    conflicts: true
    stats: true
    karma: true
    limit: true
    description: false
    usage: false
    mod: true
  kinds:
    mod: true
    karma: true
    usage: true
  items:
    category: true
    weight: true
    karma: true
    quantity: true
    mod: true
    usage: true
  events:
    usage: true
    mod: true
  animals:
    usage: true
    mod: true
    weight: true
    quantity: true
    karma: true

commands:
  # Whether or not the command list will display the command's shortcut disclaimer.
  shortcut: true
  # Whether or not the command list will display the command's required user level.
  userlevel: true
  # Whether or not the command list will display the command's uage.
  usage: true
  # Whether or not the command list will display the mod that added it.
  mod: true

mods:
  # Whether or not the mod list will display the mod's version.
  version: false
  # Whether or not the mod list will display the mod's author(s).
  author: true

# Build settings
# @see https://github.com/sylhare/Type-on-Strap/pull/406
# We can re-use `sylhare/Type-on-Strap` once merged
remote_theme: pocivaneuh/Type-on-Strap@dark-mode-improvements
plugins:
  -
